import { supabase, createAuthenticatedClient } from "../models/supabase";
import { AuthResponse, LoginRequest, RegisterRequest } from "../types/auth";
import { TablesInsert } from "../types/database.types";

export class AuthService {
  async login(credentials: LoginRequest): Promise<AuthResponse> {
    const { data, error } = await supabase.auth.signInWithPassword({
      email: credentials.email,
      password: credentials.password,
    });

    if (error) {
      throw new Error(error.message);
    }

    if (!data.session || !data.user) {
      throw new Error("Authentication failed");
    }

    return {
      user: {
        id: data.user.id,
        email: data.user.email || "",
      },
      accessToken: data.session.access_token,
      refreshToken: data.session.refresh_token,
    };
  }

  async register(userData: RegisterRequest): Promise<AuthResponse> {
    const { data, error } = await supabase.auth.signUp({
      email: userData.email,
      password: userData.password,
    });

    if (error) {
      throw new Error(error.message);
    }

    // User is created in auth.users even if session is null (email confirmation required)
    if (!data.user) {
      throw new Error("Registration failed - user not created");
    }

    // Create a record in the users table
    // Extract username from email (part before @)
    const username = userData.email.split("@")[0];

    // Insert into users table (id should be auto-generated by the database)
    // Using Omit to exclude 'id' since it's auto-generated by the database
    type UserInsertWithoutId = Omit<TablesInsert<"users">, "id">;
    const { error: userTableError } = await supabase.from("users").insert({
      email: userData.email,
      username: username,
      auth_user_id: data.user.id,
    } as UserInsertWithoutId);

    if (userTableError) {
      // If inserting into users table fails, throw an error
      // The user was created in auth.users, but we need a record in the users table
      throw new Error(
        `Failed to create user profile: ${
          userTableError.message || "Unknown error"
        }`
      );
    }

    return {
      user: {
        id: data.user.id,
        email: data.user.email || "",
      },
      accessToken: data.session?.access_token || "",
      refreshToken: data.session?.refresh_token || "",
    };
  }

  async logout(token: string): Promise<void> {
    // Create an authenticated client using the user's token
    const authenticatedClient = createAuthenticatedClient(token);

    // Sign out using the authenticated client (user session)
    const { error } = await authenticatedClient.auth.signOut();

    if (error) {
      throw new Error(error.message);
    }
  }

  async getCurrentUser(
    token: string
  ): Promise<{ id: string; email?: string } | null> {
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser(token);
    if (error) throw new Error(error.message);
    return user;
  }
}
