import type { Beer } from "./api/beer/api";

export const mockBeers: Beer[] = [
  {
    id: "1",
    name: "Heineken Lager",
    brewery: "Heineken",
    style: "Lager",
    abv: 5.0,
    ibu: 23,
    mainImage: "beer-img.jpeg",
    images: [
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
    ],
    description:
      "A pale lager beer with a crisp, refreshing taste and a mild hop character. Brewed with natural ingredients and a unique A-yeast.",
    glassType: "Pilsner Glass",
    rating: 4.3,
    numberOfRatings: 100,
  },
  {
    id: "2",
    name: "Guinness Draught",
    brewery: "Guinness",
    style: "Stout",
    abv: 4.2,
    ibu: 45,
    mainImage: "beer-img.jpeg",
    images: [
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
    ],
    description:
      "A rich, creamy stout with a distinctive surge and settle effect. Made with roasted barley for a bold, roasted flavor.",
    glassType: "Pint Glass",
    rating: 3.75,
    numberOfRatings: 100,
  },
  {
    id: "3",
    name: "Corona Extra",
    brewery: "Corona",
    style: "Lager",
    abv: 4.5,
    ibu: 18,
    mainImage: "beer-img.jpeg",
    images: [
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
    ],
    description:
      "A light, refreshing lager with a smooth taste. Best served with a wedge of lime for the authentic Corona experience.",
    glassType: "Bottle or Pilsner Glass",
    rating: 2.5,
    numberOfRatings: 100,
  },
  {
    id: "4",
    name: "Blue Moon Belgian White",
    brewery: "Blue Moon",
    style: "Wheat Beer",
    abv: 5.4,
    ibu: 9,
    mainImage: "beer-img.jpeg",
    images: [
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
    ],
    description:
      "A Belgian-style wheat ale brewed with coriander and orange peel. Smooth and creamy with a unique, refreshing flavor.",
    glassType: "Weizen Glass",
    rating: 1.75,
    numberOfRatings: 100,
  },
  {
    id: "5",
    name: "Stella Artois",
    brewery: "Stella Artois",
    style: "Pilsner",
    abv: 5.0,
    ibu: 24,
    mainImage: "beer-img.jpeg",
    images: [
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
    ],
    description:
      "A premium European lager with a crisp, clean taste. Brewed with the finest ingredients for over 600 years.",
    glassType: "Stella Artois Chalice",
    rating: 4.8,
    numberOfRatings: 100,
  },
  {
    id: "6",
    name: "IPA Craft Beer",
    brewery: "Local Brewery",
    style: "IPA",
    abv: 6.5,
    ibu: 65,
    mainImage: "beer-img.jpeg",
    images: [
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
      "beer-img.jpeg",
    ],
    description:
      "A bold India Pale Ale with intense hop flavors and aromas. Brewed with a blend of American hops for maximum flavor impact.",
    glassType: "IPA Glass",
    rating: 3.25,
    numberOfRatings: 100,
  },
];
