/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as RateBeerBeerIdRouteImport } from './routes/rate-beer/$beerId'
import { Route as BeerDetailsBeerIdRouteImport } from './routes/beer-details/$beerId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const RateBeerBeerIdRoute = RateBeerBeerIdRouteImport.update({
  id: '/rate-beer/$beerId',
  path: '/rate-beer/$beerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BeerDetailsBeerIdRoute = BeerDetailsBeerIdRouteImport.update({
  id: '/beer-details/$beerId',
  path: '/beer-details/$beerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/beer-details/$beerId': typeof BeerDetailsBeerIdRoute
  '/rate-beer/$beerId': typeof RateBeerBeerIdRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/beer-details/$beerId': typeof BeerDetailsBeerIdRoute
  '/rate-beer/$beerId': typeof RateBeerBeerIdRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/beer-details/$beerId': typeof BeerDetailsBeerIdRoute
  '/rate-beer/$beerId': typeof RateBeerBeerIdRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/beer-details/$beerId'
    | '/rate-beer/$beerId'
    | '/login'
    | '/register'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/beer-details/$beerId'
    | '/rate-beer/$beerId'
    | '/login'
    | '/register'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/beer-details/$beerId'
    | '/rate-beer/$beerId'
    | '/login/'
    | '/register/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BeerDetailsBeerIdRoute: typeof BeerDetailsBeerIdRoute
  RateBeerBeerIdRoute: typeof RateBeerBeerIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-beer/$beerId': {
      id: '/rate-beer/$beerId'
      path: '/rate-beer/$beerId'
      fullPath: '/rate-beer/$beerId'
      preLoaderRoute: typeof RateBeerBeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beer-details/$beerId': {
      id: '/beer-details/$beerId'
      path: '/beer-details/$beerId'
      fullPath: '/beer-details/$beerId'
      preLoaderRoute: typeof BeerDetailsBeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BeerDetailsBeerIdRoute: BeerDetailsBeerIdRoute,
  RateBeerBeerIdRoute: RateBeerBeerIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
