/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const SearchIndexLazyRouteImport = createFileRoute('/search/')()
const RegisterIndexLazyRouteImport = createFileRoute('/register/')()
const LoginIndexLazyRouteImport = createFileRoute('/login/')()
const RateBeerBeerIdLazyRouteImport = createFileRoute('/rate-beer/$beerId')()
const BeerDetailsBeerIdLazyRouteImport = createFileRoute(
  '/beer-details/$beerId',
)()
const AuthCallbackLazyRouteImport = createFileRoute('/auth/callback')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexLazyRoute = SearchIndexLazyRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search/index.lazy').then((d) => d.Route))
const RegisterIndexLazyRoute = RegisterIndexLazyRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/register/index.lazy').then((d) => d.Route),
)
const LoginIndexLazyRoute = LoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const RateBeerBeerIdLazyRoute = RateBeerBeerIdLazyRouteImport.update({
  id: '/rate-beer/$beerId',
  path: '/rate-beer/$beerId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/rate-beer/$beerId.lazy').then((d) => d.Route),
)
const BeerDetailsBeerIdLazyRoute = BeerDetailsBeerIdLazyRouteImport.update({
  id: '/beer-details/$beerId',
  path: '/beer-details/$beerId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/beer-details/$beerId.lazy').then((d) => d.Route),
)
const AuthCallbackLazyRoute = AuthCallbackLazyRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/callback.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackLazyRoute
  '/beer-details/$beerId': typeof BeerDetailsBeerIdLazyRoute
  '/rate-beer/$beerId': typeof RateBeerBeerIdLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/register': typeof RegisterIndexLazyRoute
  '/search': typeof SearchIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackLazyRoute
  '/beer-details/$beerId': typeof BeerDetailsBeerIdLazyRoute
  '/rate-beer/$beerId': typeof RateBeerBeerIdLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/register': typeof RegisterIndexLazyRoute
  '/search': typeof SearchIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackLazyRoute
  '/beer-details/$beerId': typeof BeerDetailsBeerIdLazyRoute
  '/rate-beer/$beerId': typeof RateBeerBeerIdLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/register/': typeof RegisterIndexLazyRoute
  '/search/': typeof SearchIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/beer-details/$beerId'
    | '/rate-beer/$beerId'
    | '/login'
    | '/register'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/beer-details/$beerId'
    | '/rate-beer/$beerId'
    | '/login'
    | '/register'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/beer-details/$beerId'
    | '/rate-beer/$beerId'
    | '/login/'
    | '/register/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackLazyRoute: typeof AuthCallbackLazyRoute
  BeerDetailsBeerIdLazyRoute: typeof BeerDetailsBeerIdLazyRoute
  RateBeerBeerIdLazyRoute: typeof RateBeerBeerIdLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  RegisterIndexLazyRoute: typeof RegisterIndexLazyRoute
  SearchIndexLazyRoute: typeof SearchIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-beer/$beerId': {
      id: '/rate-beer/$beerId'
      path: '/rate-beer/$beerId'
      fullPath: '/rate-beer/$beerId'
      preLoaderRoute: typeof RateBeerBeerIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beer-details/$beerId': {
      id: '/beer-details/$beerId'
      path: '/beer-details/$beerId'
      fullPath: '/beer-details/$beerId'
      preLoaderRoute: typeof BeerDetailsBeerIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackLazyRoute: AuthCallbackLazyRoute,
  BeerDetailsBeerIdLazyRoute: BeerDetailsBeerIdLazyRoute,
  RateBeerBeerIdLazyRoute: RateBeerBeerIdLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  RegisterIndexLazyRoute: RegisterIndexLazyRoute,
  SearchIndexLazyRoute: SearchIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
